### ISSUE TITLE
ios : duplicate symbol '_OBJC_CLASS_$_TOActivityCroppedImageProvider'

### ISSUE THREAD

**Issue by sarafhbk** [baronha/react-native-multiple-image-picker#108]
ios build error after updating from 0.4.10 -> 1.0.0.

i tried all these steps

delete pod lock , remove pods and pod install
remove derived data
clean build

but no luck..

`duplicate symbol '_OBJC_CLASS_$_TOActivityCroppedImageProvider' in:
    /Users/saraf/Library/Developer/Xcode/DerivedData/UrduReader-hfoqbatrmtjnvkcmihfuiugtxjva/Build/Products/StageDebug-iphonesimulator/CropViewController/libCropViewController.a(TOActivityCroppedImageProvider.o)
    /Users/saraf/Library/Developer/Xcode/DerivedData/UrduReader-hfoqbatrmtjnvkcmihfuiugtxjva/Build/Products/StageDebug-iphonesimulator/TOCropViewController/libTOCropViewController.a(TOActivityCroppedImageProvider.o)
duplicate symbol '_OBJC_METACLASS_$_TOActivityCroppedImageProvider' in:
.......
.......

ld: 157 duplicate symbols for architecture x86_64`

**Comment by baronha** [comment]
Please try to refer to the solutions below. Hope it will be useful: 
- https://github.com/facebook/react-native/issues/27840
- https://github.com/facebook/react-native/issues/32016
- https://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64-under-xcode

**Comment by sarafhbk** [comment]
@baronha Thanks for the respons. I tried all these for the past 2 days, but nothing worked.

**Comment by baronha** [comment]
> @baronha Thanks for the respons. I tried all these for the past 2 days, but nothing worked.

Have you tried this yet?
https://stackoverflow.com/questions/52536380/why-do-i-get-ios-linker-errors-with-my-static-libraries

**Comment by sarafhbk** [comment]
@baronha  I already added the Swift file and headers.

the second link which u shared says add pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper',
do we have anything like this for CropViewController?

**Comment by sarafhbk** [comment]
@baronha what should i try? adding what in place of RNCharts?

**Comment by baronha** [comment]
Wait. I think this error is mainly in your Flipper configuration. Show me your Podfile

**Comment by sarafhbk** [comment]
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!


project 'UrduReader', {
        'StageDebug' => :debug,
        'StageRelease' => :release, 
        'Debug' => :debug,
        'Release' => :release
}


# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled(['Debug', 'StageDebug', 'Release', 'StageRelease'], { 'Flipper' => '0.193.0' })

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'UrduReader' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera', :modular_headers => true

  target 'UrduReaderTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
  end
  
  target 'share' do
    use_react_native!
  
    pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
    # Manually link packages here to keep your extension bundle size minimal

  end

  # react-native-permissions permission handlers
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency/Permission-AppTrackingTransparency.podspec"
  # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral/Permission-BluetoothPeripheral.podspec"
  # pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars/Permission-Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts/Permission-Contacts.podspec"
  # pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID/Permission-FaceID.podspec"
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary/Permission-MediaLibrary.podspec"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone/Permission-Microphone.podspec"
  # pod 'Permission-Motion', :path => "#{permissions_path}/Motion/Permission-Motion.podspec"
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications/Permission-Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
  # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders/Permission-Reminders.podspec"
  # pod 'Permission-Siri', :path => "#{permissions_path}/Siri/Permission-Siri.podspec"
  # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition/Permission-SpeechRecognition.podspec"
  # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit/Permission-StoreKit.podspec"
  
end
`



@baronha

**Comment by baronha** [comment]
@sarafhbk I think if you use this library it is not necessary to use additional `pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'
`

**Comment by sarafhbk** [comment]
@baronha after removing the pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'  also the error still remains. i use this package because i need a standalone image cropper for edit image feature.

**Comment by baronha** [comment]
> @baronha after removing the pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools' also the error still remains. i use this package because i need a standalone image cropper for edit image feature.

standalone image cropper will be deployed in the future in react-native-multiple-image-picker@latest.
Back to the above error. You have deleted `Podfile.lock` & `/Pod` and re-installed `pod-install`

**Comment by sarafhbk** [comment]
@baronha yes i did that. I think the issue might be both packages use TOActivityCroppedImageProvider in common.

**Comment by sarafhbk** [comment]
@baronha do u suggest anything? im stuck with this issue for a very long time. everytime i had to change the version for ios and then make builds

**Comment by fukemy** [comment]
this error say that you have duplicate class named like TOActivityCroppedImageProvider, let search and find another lib use this class. 
 1. If you does not tend to use this lib that have same class too, just remove it, then problem will gone
 2. If you must do this, so you need to fork one lib as local library then modify the filename
